version: "3.9"

services:
  gcloud:
    image: "google/cloud-sdk:410.0.0"
    volumes:
      - gcp-creds:/creds
      - .:/socialmediadashboard
    working_dir: /socialmediadashboard
    environment:
      - CLOUDSDK_CONFIG=/creds

volumes:
  gcp-creds:
