version: "3.9"

services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./socialmediadashboard:/socialmediadashboard
    command: python manage.py runserver 0.0.0.0:8000
    environment: -DEBUG=1
