# Generated by Django 4.1.3 on 2022-11-15 12:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDashboardData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=2000, null=True)),
                ('postid', models.CharField(max_length=500, null=True)),
                ('network', models.CharField(max_length=500, null=True)),
                ('date_posted', models.DateTimeField(null=True)),
                ('text_content', models.CharField(max_length=2000, null=True)),
                ('media_content', models.CharField(max_length=2000, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('language', models.CharField(max_length=500, null=True)),
                ('sentiment', models.CharField(max_length=500, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('post_url', models.URLField(max_length=2000, null=True)),
                ('profile_name', models.CharField(max_length=500, null=True)),
                ('profile_picture', models.URLField(max_length=2000, null=True)),
                ('twitter_followers', models.IntegerField(default=0, null=True)),
                ('engagements', models.JSONField(default=dict, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
