# Generated by Django 4.1.3 on 2022-11-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_socialdashboarddata_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialdashboarddata',
            name='language',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='socialdashboarddata',
            name='network',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='socialdashboarddata',
            name='postid',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='socialdashboarddata',
            name='profile_name',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='socialdashboarddata',
            name='sentiment',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
